// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fallback para evitar crash visual no ambiente Lovable quando a conexão falha
const URL = SUPABASE_URL || 'https://opbnkyezpbaeoujgdwty.supabase.co';
const KEY = SUPABASE_PUBLISHABLE_KEY || 'missing-key';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("⚠️ Atencao: Variáveis de ambiente do Supabase nao detectadas. Usando configuracao de fallback.");
}

export const supabase = createClient<Database>(URL, KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});